# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_AddUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 457)
        MainWindow.setStyleSheet("background-color: rgb(58, 58,58);\n"
"QLineEdit{\n"
"    color:white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.lb_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lb_title.setFont(font)
        self.lb_title.setStyleSheet("font-size:40px;\n"
"                                            color:rgb(255,255,255);\n"
"                                            font:Arial;\n"
"                                        ")
        self.lb_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_title.setObjectName("lb_title")
        self.verticalLayout.addWidget(self.lb_title)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.lb_username = QtWidgets.QLabel(self.centralwidget)
        self.lb_username.setStyleSheet("font-family:Arial;\n"
"                                            font-size:25px;\n"
"\n"
"                                            color:rgb(255, 255, 255)\n"
"                                        ")
        self.lb_username.setObjectName("lb_username")
        self.horizontalLayout.addWidget(self.lb_username)
        self.le_id = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.le_id.setFont(font)
        self.le_id.setStyleSheet("color:rgb(255, 255, 255);\n"
"                                            background-color:rgb(50,60,70);\n"
"                                        ")
        self.le_id.setAlignment(QtCore.Qt.AlignCenter)
        self.le_id.setObjectName("le_id")
        self.horizontalLayout.addWidget(self.le_id)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.lb_name = QtWidgets.QLabel(self.centralwidget)
        self.lb_name.setStyleSheet("font-family:Arial;\n"
"                                            font-size:25px;\n"
"\n"
"                                            color:rgb(255, 255, 255)\n"
"                                        ")
        self.lb_name.setObjectName("lb_name")
        self.horizontalLayout_2.addWidget(self.lb_name)
        self.le_username = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.le_username.setFont(font)
        self.le_username.setStyleSheet("color:rgb(255, 255, 255);\n"
"                                            background-color:rgb(50,60,70);\n"
"                                        ")
        self.le_username.setAlignment(QtCore.Qt.AlignCenter)
        self.le_username.setObjectName("le_username")
        self.horizontalLayout_2.addWidget(self.le_username)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(37, 29, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.lb_sex = QtWidgets.QLabel(self.centralwidget)
        self.lb_sex.setStyleSheet("font-family:Arial;\n"
"                                            font-size:25px;\n"
"\n"
"                                            color:rgb(255, 255, 255)\n"
"                                        ")
        self.lb_sex.setObjectName("lb_sex")
        self.horizontalLayout_3.addWidget(self.lb_sex)
        self.cb_gender = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_gender.sizePolicy().hasHeightForWidth())
        self.cb_gender.setSizePolicy(sizePolicy)
        self.cb_gender.setMinimumSize(QtCore.QSize(0, 0))
        self.cb_gender.setMaximumSize(QtCore.QSize(222, 32))
        self.cb_gender.setStyleSheet("font-family:Arial;\n"
"                                            font-size:25px;\n"
"\n"
"                                            color:rgb(255, 255, 255)\n"
"                                        ")
        self.cb_gender.setObjectName("cb_gender")
        self.cb_gender.addItem("")
        self.cb_gender.addItem("")
        self.horizontalLayout_3.addWidget(self.cb_gender)
        spacerItem9 = QtWidgets.QSpacerItem(37, 29, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.lb_tel = QtWidgets.QLabel(self.centralwidget)
        self.lb_tel.setStyleSheet("font-family:Arial;\n"
"                                            font-size:25px;\n"
"\n"
"                                            color:rgb(255, 255, 255)\n"
"                                        ")
        self.lb_tel.setObjectName("lb_tel")
        self.horizontalLayout_4.addWidget(self.lb_tel)
        self.le_mobile = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.le_mobile.setFont(font)
        self.le_mobile.setStyleSheet("color:rgb(255, 255, 255);\n"
"                                            background-color:rgb(50,60,70);\n"
"                                        ")
        self.le_mobile.setAlignment(QtCore.Qt.AlignCenter)
        self.le_mobile.setObjectName("le_mobile")
        self.horizontalLayout_4.addWidget(self.le_mobile)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem13)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.lb_depart = QtWidgets.QLabel(self.centralwidget)
        self.lb_depart.setStyleSheet("font-family:Arial;\n"
"                                            font-size:25px;\n"
"\n"
"                                            color:rgb(255, 255, 255)\n"
"                                        ")
        self.lb_depart.setObjectName("lb_depart")
        self.horizontalLayout_5.addWidget(self.lb_depart)
        self.le_depart = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.le_depart.setFont(font)
        self.le_depart.setStyleSheet("color:rgb(255, 255, 255);\n"
"                                            background-color:rgb(50,60,70);\n"
"                                        ")
        self.le_depart.setAlignment(QtCore.Qt.AlignCenter)
        self.le_depart.setObjectName("le_depart")
        self.horizontalLayout_5.addWidget(self.le_depart)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem16)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem17)
        self.lb_password = QtWidgets.QLabel(self.centralwidget)
        self.lb_password.setStyleSheet("font-family:Arial;\n"
"                                            font-size:25px;\n"
"\n"
"                                            color:rgb(255, 255, 255)\n"
"                                        ")
        self.lb_password.setObjectName("lb_password")
        self.horizontalLayout_6.addWidget(self.lb_password)
        self.le_password = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.le_password.setFont(font)
        self.le_password.setStyleSheet("color:rgb(255, 255, 255);\n"
"                                            background-color:rgb(50,60,70);\n"
"                                        ")
        self.le_password.setAlignment(QtCore.Qt.AlignCenter)
        self.le_password.setObjectName("le_password")
        self.horizontalLayout_6.addWidget(self.le_password)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem18)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem19)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem20)
        self.pb_clearAll = QtWidgets.QPushButton(self.centralwidget)
        self.pb_clearAll.setStyleSheet("QPushButton {\n"
"                                                    color: #ffffff;\n"
"                                                    background-color: rgb(40,40, 60);\n"
"                                                    border-radius:5px;\n"
"                                                    text-align:center;\n"
"                                                    font-size:20pt;\n"
"                                                    font-family:Arial;\n"
"                                                    padding: 5px;\n"
"                                                    border:2px solid rgb(67,83,180);\n"
"                                                    }\n"
"                                                    QPushButton:hover{\n"
"                                                    font-size:20pt;\n"
"                                                    font-weight:bold;\n"
"                                                    border-width:4px;\n"
"                                                    border-radius:10px;\n"
"                                                    }\n"
"                                                ")
        self.pb_clearAll.setObjectName("pb_clearAll")
        self.horizontalLayout_7.addWidget(self.pb_clearAll)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem21)
        self.pb_addUser = QtWidgets.QPushButton(self.centralwidget)
        self.pb_addUser.setStyleSheet("QPushButton {\n"
"                                                    color: #ffffff;\n"
"                                                    background-color: rgb(40,40, 60);\n"
"                                                    border-radius:5px;\n"
"                                                    text-align:center;\n"
"                                                    font-size:20pt;\n"
"                                                    font-family:Arial;\n"
"                                                    padding: 5px;\n"
"                                                    border:2px solid rgb(67,83,180);\n"
"                                                    }\n"
"                                                    QPushButton:hover{\n"
"                                                    font-size:20pt;\n"
"                                                    font-weight:bold;\n"
"                                                    border-width:4px;\n"
"                                                    border-radius:10px;\n"
"                                                    }\n"
"                                                ")
        self.pb_addUser.setObjectName("pb_addUser")
        self.horizontalLayout_7.addWidget(self.pb_addUser)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem22)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem23)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pb_clearAll.clicked.connect(MainWindow.cleanAll) # type: ignore
        self.pb_addUser.clicked.connect(MainWindow.addUser) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_title.setText(_translate("MainWindow", "添加用户"))
        self.lb_username.setText(_translate("MainWindow", "账号ID："))
        self.lb_name.setText(_translate("MainWindow", "姓    名："))
        self.lb_sex.setText(_translate("MainWindow", "性    别："))
        self.cb_gender.setItemText(0, _translate("MainWindow", "男"))
        self.cb_gender.setItemText(1, _translate("MainWindow", "女"))
        self.lb_tel.setText(_translate("MainWindow", "电    话："))
        self.lb_depart.setText(_translate("MainWindow", "部    门："))
        self.lb_password.setText(_translate("MainWindow", "密    码："))
        self.pb_clearAll.setText(_translate("MainWindow", "清除"))
        self.pb_addUser.setText(_translate("MainWindow", "添加"))
