# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_InsProtect.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1392, 755)
        MainWindow.setStyleSheet("background-color: rgb(58, 58,58);\n"
"QLineEdit{\n"
"    color:white;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_16.addLayout(self.verticalLayout_8)
        spacerItem = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_16.addLayout(self.horizontalLayout_9)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:white;\n"
"font: 75 40pt \"Arial\";\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_16.addWidget(self.label_9)
        spacerItem1 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("color:white;\n"
"font: 75 14pt \"Arial\";\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(1268, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.verticalLayout_16.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_16.addLayout(self.verticalLayout_7)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet("QCheckBox{\n"
"color: rgb(255, 255, 255);\n"
"};\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(176, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cb_ins_115ac = QtWidgets.QCheckBox(self.groupBox)
        self.cb_ins_115ac.setEnabled(False)
        self.cb_ins_115ac.setStyleSheet("QCheckBox{\n"
"\n"
"color:white;\n"
"font: 75 14pt \"Arial\";\n"
"}\n"
"QCheckBox:unchecked{\n"
"    color:red;\n"
"}\n"
"QCheckBox:checked{\n"
"    color:rgb(0, 170, 0);\n"
"}")
        self.cb_ins_115ac.setObjectName("cb_ins_115ac")
        self.verticalLayout_3.addWidget(self.cb_ins_115ac)
        self.cb_ins_28dc1 = QtWidgets.QCheckBox(self.groupBox)
        self.cb_ins_28dc1.setEnabled(False)
        self.cb_ins_28dc1.setStyleSheet("QCheckBox{\n"
"\n"
"color:white;\n"
"font: 75 14pt \"Arial\";\n"
"}\n"
"QCheckBox:unchecked{\n"
"    color:red;\n"
"}\n"
"QCheckBox:checked{\n"
"    color:rgb(0, 170, 0);\n"
"}")
        self.cb_ins_28dc1.setObjectName("cb_ins_28dc1")
        self.verticalLayout_3.addWidget(self.cb_ins_28dc1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.cb_ins_28dc2 = QtWidgets.QCheckBox(self.groupBox)
        self.cb_ins_28dc2.setEnabled(False)
        self.cb_ins_28dc2.setStyleSheet("QCheckBox{\n"
"\n"
"color:white;\n"
"font: 75 14pt \"Arial\";\n"
"}\n"
"QCheckBox:unchecked{\n"
"    color:red;\n"
"}\n"
"QCheckBox:checked{\n"
"    color:rgb(0, 170, 0);\n"
"}")
        self.cb_ins_28dc2.setObjectName("cb_ins_28dc2")
        self.verticalLayout_13.addWidget(self.cb_ins_28dc2)
        self.cb_ins_card = QtWidgets.QCheckBox(self.groupBox)
        self.cb_ins_card.setEnabled(False)
        self.cb_ins_card.setStyleSheet("QCheckBox{\n"
"\n"
"color:white;\n"
"font: 75 14pt \"Arial\";\n"
"}\n"
"QCheckBox:unchecked{\n"
"    color:red;\n"
"}\n"
"QCheckBox:checked{\n"
"    color:rgb(0, 170, 0);\n"
"}")
        self.cb_ins_card.setObjectName("cb_ins_card")
        self.verticalLayout_13.addWidget(self.cb_ins_card)
        self.horizontalLayout.addLayout(self.verticalLayout_13)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.cb_ins_asg = QtWidgets.QCheckBox(self.groupBox)
        self.cb_ins_asg.setEnabled(False)
        self.cb_ins_asg.setStyleSheet("QCheckBox{\n"
"\n"
"color:white;\n"
"font: 75 14pt \"Arial\";\n"
"}\n"
"QCheckBox:unchecked{\n"
"    color:red;\n"
"}\n"
"QCheckBox:checked{\n"
"    color:rgb(0, 170, 0);\n"
"}")
        self.cb_ins_asg.setObjectName("cb_ins_asg")
        self.verticalLayout_9.addWidget(self.cb_ins_asg)
        self.cb_ins_dsg = QtWidgets.QCheckBox(self.groupBox)
        self.cb_ins_dsg.setEnabled(False)
        self.cb_ins_dsg.setStyleSheet("QCheckBox{\n"
"\n"
"color:white;\n"
"font: 75 14pt \"Arial\";\n"
"}\n"
"QCheckBox:unchecked{\n"
"    color:red;\n"
"}\n"
"QCheckBox:checked{\n"
"    color:rgb(0, 170, 0);\n"
"}")
        self.cb_ins_dsg.setObjectName("cb_ins_dsg")
        self.verticalLayout_9.addWidget(self.cb_ins_dsg)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.cb_ins_dataget = QtWidgets.QCheckBox(self.groupBox)
        self.cb_ins_dataget.setEnabled(False)
        self.cb_ins_dataget.setStyleSheet("QCheckBox{\n"
"\n"
"color:white;\n"
"font: 75 14pt \"Arial\";\n"
"}\n"
"QCheckBox:unchecked{\n"
"    color:red;\n"
"}\n"
"QCheckBox:checked{\n"
"    color:rgb(0, 170, 0);\n"
"}")
        self.cb_ins_dataget.setObjectName("cb_ins_dataget")
        self.verticalLayout_11.addWidget(self.cb_ins_dataget)
        self.cb_ins_currget = QtWidgets.QCheckBox(self.groupBox)
        self.cb_ins_currget.setEnabled(False)
        self.cb_ins_currget.setStyleSheet("QCheckBox{\n"
"\n"
"color:white;\n"
"font: 75 14pt \"Arial\";\n"
"}\n"
"QCheckBox:unchecked{\n"
"    color:red;\n"
"}\n"
"QCheckBox:checked{\n"
"    color:rgb(0, 170, 0);\n"
"}")
        self.cb_ins_currget.setObjectName("cb_ins_currget")
        self.verticalLayout_11.addWidget(self.cb_ins_currget)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.cb_ins_dcard = QtWidgets.QCheckBox(self.groupBox)
        self.cb_ins_dcard.setEnabled(False)
        self.cb_ins_dcard.setStyleSheet("QCheckBox{\n"
"\n"
"color:white;\n"
"font: 75 14pt \"Arial\";\n"
"}\n"
"QCheckBox:unchecked{\n"
"    color:red;\n"
"}\n"
"QCheckBox:checked{\n"
"    color:rgb(0, 170, 0);\n"
"}")
        self.cb_ins_dcard.setObjectName("cb_ins_dcard")
        self.verticalLayout_10.addWidget(self.cb_ins_dcard)
        self.cb_ins_LR = QtWidgets.QCheckBox(self.groupBox)
        self.cb_ins_LR.setEnabled(False)
        self.cb_ins_LR.setStyleSheet("QCheckBox{\n"
"\n"
"color:white;\n"
"font: 75 14pt \"Arial\";\n"
"}\n"
"QCheckBox:unchecked{\n"
"    color:red;\n"
"}\n"
"QCheckBox:checked{\n"
"    color:rgb(0, 170, 0);\n"
"}")
        self.cb_ins_LR.setObjectName("cb_ins_LR")
        self.verticalLayout_10.addWidget(self.cb_ins_LR)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.cb_ins_429 = QtWidgets.QCheckBox(self.groupBox)
        self.cb_ins_429.setEnabled(False)
        self.cb_ins_429.setStyleSheet("QCheckBox{\n"
"\n"
"color:white;\n"
"font: 75 14pt \"Arial\";\n"
"}\n"
"QCheckBox:unchecked{\n"
"    color:red;\n"
"}\n"
"QCheckBox:checked{\n"
"    color:rgb(0, 170, 0);\n"
"}")
        self.cb_ins_429.setObjectName("cb_ins_429")
        self.verticalLayout_12.addWidget(self.cb_ins_429)
        self.cb_ins_232 = QtWidgets.QCheckBox(self.groupBox)
        self.cb_ins_232.setEnabled(False)
        self.cb_ins_232.setStyleSheet("QCheckBox{\n"
"\n"
"color:white;\n"
"font: 75 14pt \"Arial\";\n"
"}\n"
"QCheckBox:unchecked{\n"
"    color:red;\n"
"}\n"
"QCheckBox:checked{\n"
"    color:rgb(0, 170, 0);\n"
"}")
        self.cb_ins_232.setObjectName("cb_ins_232")
        self.verticalLayout_12.addWidget(self.cb_ins_232)
        self.horizontalLayout.addLayout(self.verticalLayout_12)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(175, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.pb_ins_confirm = QtWidgets.QPushButton(self.groupBox)
        self.pb_ins_confirm.setStyleSheet("QPushButton{\n"
"background-color:rgb(33,37,43);\n"
"color:white;\n"
"font: 14pt \"Arial\";\n"
"border:3px solid rgb(29,63,91);\n"
"border-radius:5px;\n"
"padding-right:20px;\n"
"padding-left:20px;\n"
"padding-top:5px;\n"
"padding-bottom:5px;}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"font-size:17pt;\n"
"font-weight:bold;\n"
"border-width:4px;\n"
"border-radius:5px;\n"
"padding-right:0px;\n"
"padding-left:0px;\n"
"padding-top:5px;\n"
"padding-bottom:5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(85, 170, 255);\n"
"}")
        self.pb_ins_confirm.setObjectName("pb_ins_confirm")
        self.horizontalLayout_4.addWidget(self.pb_ins_confirm)
        spacerItem5 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_16.addWidget(self.groupBox)
        spacerItem6 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;\n"
"font: 75 14pt \"Arial\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        spacerItem7 = QtWidgets.QSpacerItem(1158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.verticalLayout_16.addLayout(self.horizontalLayout_7)
        self.frame_prot = QtWidgets.QFrame(self.centralwidget)
        self.frame_prot.setStyleSheet("QFrame#frame_prot{\n"
"border-right:2px solid gray;\n"
"border-left:2px solid gray;\n"
"border-top:2px solid  gray;\n"
"border-bottom:2px solid  gray;\n"
"border-radius:10px;\n"
"}")
        self.frame_prot.setObjectName("frame_prot")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_prot)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.frame_28V = QtWidgets.QFrame(self.frame_prot)
        self.frame_28V.setStyleSheet("QFrame#frame_28V{\n"
"border-right:2px solid gray;\n"
"border-left:2px solid gray;\n"
"border-top:2px solid  gray;\n"
"border-bottom:2px solid  gray;\n"
"border-radius:10px;\n"
"}")
        self.frame_28V.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28V.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28V.setObjectName("frame_28V")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_28V)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem9 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self._28_verticalLayout = QtWidgets.QVBoxLayout()
        self._28_verticalLayout.setObjectName("_28_verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_28V)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;\n"
"font: 75 14pt \"Arial\";\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self._28_verticalLayout.addWidget(self.label_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.frame_28V)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:white;\n"
"font: 75 14pt \"Arial\";")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.le_pro_dc_overcur = QtWidgets.QLineEdit(self.frame_28V)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_pro_dc_overcur.sizePolicy().hasHeightForWidth())
        self.le_pro_dc_overcur.setSizePolicy(sizePolicy)
        self.le_pro_dc_overcur.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(8)
        self.le_pro_dc_overcur.setFont(font)
        self.le_pro_dc_overcur.setStyleSheet("color:white;\n"
"background-color: rgb(0, 0, 0);\n"
"font: 65 14pt \"Arial\";")
        self.le_pro_dc_overcur.setAlignment(QtCore.Qt.AlignCenter)
        self.le_pro_dc_overcur.setObjectName("le_pro_dc_overcur")
        self.horizontalLayout_2.addWidget(self.le_pro_dc_overcur)
        self.label_4 = QtWidgets.QLabel(self.frame_28V)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;\n"
"font: 75 14pt \"Arial\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.frame_28V)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:white;\n"
"font: 75 14pt \"Arial\";")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.le_pro_dc_overvolt = QtWidgets.QLineEdit(self.frame_28V)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_pro_dc_overvolt.sizePolicy().hasHeightForWidth())
        self.le_pro_dc_overvolt.setSizePolicy(sizePolicy)
        self.le_pro_dc_overvolt.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(8)
        self.le_pro_dc_overvolt.setFont(font)
        self.le_pro_dc_overvolt.setStyleSheet("color:white;\n"
"background-color: rgb(0, 0, 0);\n"
"font: 65 14pt \"Arial\";")
        self.le_pro_dc_overvolt.setAlignment(QtCore.Qt.AlignCenter)
        self.le_pro_dc_overvolt.setObjectName("le_pro_dc_overvolt")
        self.horizontalLayout_3.addWidget(self.le_pro_dc_overvolt)
        self.label_7 = QtWidgets.QLabel(self.frame_28V)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:white;\n"
"font: 75 14pt \"Arial\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self._28_verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6.addLayout(self._28_verticalLayout)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        spacerItem10 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem10)
        self.verticalLayout_15.addLayout(self.verticalLayout_5)
        self.horizontalLayout_10.addWidget(self.frame_28V)
        self.frame115Vdc = QtWidgets.QFrame(self.frame_prot)
        self.frame115Vdc.setStyleSheet("QFrame#frame115Vdc{\n"
"border-right:2px solid gray;\n"
"border-left:2px solid gray;\n"
"border-top:2px solid  gray;\n"
"border-bottom:2px solid  gray;\n"
"border-radius:10px;\n"
"}")
        self.frame115Vdc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame115Vdc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame115Vdc.setObjectName("frame115Vdc")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame115Vdc)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_8 = QtWidgets.QLabel(self.frame115Vdc)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:white;\n"
"font: 75 14pt \"Arial\";\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_14.addWidget(self.label_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame115Vdc)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.rb_pro_adc_single = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.rb_pro_adc_single.setFont(font)
        self.rb_pro_adc_single.setStyleSheet("QRadioButton{\n"
"    color:white;\n"
"    font: 75 14pt \"Arial\";\n"
"}\n"
"QRadioButton:unchecked{\n"
"    color:gray;\n"
"}\n"
"\n"
"QRadioButton:checked{\n"
"    color:rgb(0,170,0);\n"
"}\n"
"")
        self.rb_pro_adc_single.setChecked(True)
        self.rb_pro_adc_single.setObjectName("rb_pro_adc_single")
        self.verticalLayout_17.addWidget(self.rb_pro_adc_single)
        self.horizontalLayout_5.addWidget(self.groupBox_2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame115Vdc)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.rb_pro_adc_low = QtWidgets.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.rb_pro_adc_low.setFont(font)
        self.rb_pro_adc_low.setStyleSheet("QRadioButton{\n"
"    color:white;\n"
"    font: 75 14pt \"Arial\";\n"
"}\n"
"QRadioButton:unchecked{\n"
"    color:gray;\n"
"}\n"
"\n"
"QRadioButton:checked{\n"
"    color:rgb(0,170,0);\n"
"}\n"
"")
        self.rb_pro_adc_low.setChecked(True)
        self.rb_pro_adc_low.setObjectName("rb_pro_adc_low")
        self.horizontalLayout_11.addWidget(self.rb_pro_adc_low)
        self.rb_pro_adc_high = QtWidgets.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.rb_pro_adc_high.setFont(font)
        self.rb_pro_adc_high.setStyleSheet("QRadioButton{\n"
"    color:white;\n"
"    font: 75 14pt \"Arial\";\n"
"}\n"
"QRadioButton:unchecked{\n"
"    color:gray;\n"
"}\n"
"\n"
"QRadioButton:checked{\n"
"    color:rgb(0,170,0);\n"
"}\n"
"")
        self.rb_pro_adc_high.setObjectName("rb_pro_adc_high")
        self.horizontalLayout_11.addWidget(self.rb_pro_adc_high)
        self.horizontalLayout_23.addWidget(self.groupBox_3)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_23)
        spacerItem12 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_43 = QtWidgets.QLabel(self.frame115Vdc)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("color:white;\n"
"font: 75 14pt \"Arial\";")
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout.addWidget(self.label_43, 2, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.frame115Vdc)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("color:white;\n"
"font: 75 14pt \"Arial\";")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout.addWidget(self.label_40, 0, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.frame115Vdc)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("color:white;\n"
"font: 75 14pt \"Arial\";")
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout.addWidget(self.label_42, 1, 2, 1, 1)
        self.le_pro_ac_overvolt = QtWidgets.QLineEdit(self.frame115Vdc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_pro_ac_overvolt.sizePolicy().hasHeightForWidth())
        self.le_pro_ac_overvolt.setSizePolicy(sizePolicy)
        self.le_pro_ac_overvolt.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(8)
        self.le_pro_ac_overvolt.setFont(font)
        self.le_pro_ac_overvolt.setStyleSheet("color:white;\n"
"background-color: rgb(0, 0, 0);\n"
"font: 65 14pt \"Arial\";")
        self.le_pro_ac_overvolt.setAlignment(QtCore.Qt.AlignCenter)
        self.le_pro_ac_overvolt.setObjectName("le_pro_ac_overvolt")
        self.gridLayout.addWidget(self.le_pro_ac_overvolt, 1, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.frame115Vdc)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("color:white;\n"
"font: 75 14pt \"Arial\";")
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout.addWidget(self.label_41, 1, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.frame115Vdc)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color:white;\n"
"font: 75 14pt \"Arial\";")
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout.addWidget(self.label_39, 0, 0, 1, 1)
        self.le_pro_ac_overcur = QtWidgets.QLineEdit(self.frame115Vdc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_pro_ac_overcur.sizePolicy().hasHeightForWidth())
        self.le_pro_ac_overcur.setSizePolicy(sizePolicy)
        self.le_pro_ac_overcur.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(8)
        self.le_pro_ac_overcur.setFont(font)
        self.le_pro_ac_overcur.setStyleSheet("color:white;\n"
"background-color: rgb(0, 0, 0);\n"
"font: 65 14pt \"Arial\";")
        self.le_pro_ac_overcur.setAlignment(QtCore.Qt.AlignCenter)
        self.le_pro_ac_overcur.setObjectName("le_pro_ac_overcur")
        self.gridLayout.addWidget(self.le_pro_ac_overcur, 0, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.frame115Vdc)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("color:white;\n"
"font: 75 14pt \"Arial\";")
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout.addWidget(self.label_45, 3, 0, 1, 1)
        self.le_pro_ac_lowvolt = QtWidgets.QLineEdit(self.frame115Vdc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_pro_ac_lowvolt.sizePolicy().hasHeightForWidth())
        self.le_pro_ac_lowvolt.setSizePolicy(sizePolicy)
        self.le_pro_ac_lowvolt.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(8)
        self.le_pro_ac_lowvolt.setFont(font)
        self.le_pro_ac_lowvolt.setStyleSheet("color:white;\n"
"background-color: rgb(0, 0, 0);\n"
"font: 65 14pt \"Arial\";")
        self.le_pro_ac_lowvolt.setAlignment(QtCore.Qt.AlignCenter)
        self.le_pro_ac_lowvolt.setObjectName("le_pro_ac_lowvolt")
        self.gridLayout.addWidget(self.le_pro_ac_lowvolt, 2, 1, 1, 1)
        self.le_pro_ac_overPpro = QtWidgets.QLineEdit(self.frame115Vdc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_pro_ac_overPpro.sizePolicy().hasHeightForWidth())
        self.le_pro_ac_overPpro.setSizePolicy(sizePolicy)
        self.le_pro_ac_overPpro.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(8)
        self.le_pro_ac_overPpro.setFont(font)
        self.le_pro_ac_overPpro.setStyleSheet("color:white;\n"
"background-color: rgb(0, 0, 0);\n"
"font: 65 14pt \"Arial\";")
        self.le_pro_ac_overPpro.setAlignment(QtCore.Qt.AlignCenter)
        self.le_pro_ac_overPpro.setObjectName("le_pro_ac_overPpro")
        self.gridLayout.addWidget(self.le_pro_ac_overPpro, 3, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.frame115Vdc)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("color:white;\n"
"font: 75 14pt \"Arial\";")
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout.addWidget(self.label_44, 2, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.frame115Vdc)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("color:white;\n"
"font: 75 14pt \"Arial\";")
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout.addWidget(self.label_46, 3, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_4.addLayout(self.verticalLayout_18)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_14.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_10.addWidget(self.frame115Vdc)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem13)
        self.pb_pro = QtWidgets.QPushButton(self.frame_prot)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pb_pro.setFont(font)
        self.pb_pro.setStyleSheet("QPushButton{\n"
"background-color:rgb(33,37,43);\n"
"color:white;\n"
"font: 14pt \"Arial\";\n"
"border:3px solid rgb(29,63,91);\n"
"border-radius:5px;\n"
"padding-right:20px;\n"
"padding-left:20px;\n"
"padding-top:5px;\n"
"padding-bottom:5px;}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"font-size:17pt;\n"
"font-weight:bold;\n"
"border-width:4px;\n"
"border-radius:5px;\n"
"padding-right:0px;\n"
"padding-left:0px;\n"
"padding-top:5px;\n"
"padding-bottom:5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(85, 170, 255);\n"
"}")
        self.pb_pro.setObjectName("pb_pro")
        self.horizontalLayout_10.addWidget(self.pb_pro)
        spacerItem14 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem14)
        self.verticalLayout_16.addWidget(self.frame_prot)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem15)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "设备自检"))
        self.label_9.setText(_translate("MainWindow", "设备自检与保护设定"))
        self.label.setText(_translate("MainWindow", "设备自检"))
        self.cb_ins_115ac.setText(_translate("MainWindow", "115交流电源"))
        self.cb_ins_28dc1.setText(_translate("MainWindow", "28V直流电源1"))
        self.cb_ins_28dc2.setText(_translate("MainWindow", "28V直流电源2"))
        self.cb_ins_card.setText(_translate("MainWindow", "热电偶卡与热电阻卡"))
        self.cb_ins_asg.setText(_translate("MainWindow", "交流信号发生器"))
        self.cb_ins_dsg.setText(_translate("MainWindow", "直流信号发生器"))
        self.cb_ins_dataget.setText(_translate("MainWindow", "数据采集卡"))
        self.cb_ins_currget.setText(_translate("MainWindow", "电流采集"))
        self.cb_ins_dcard.setText(_translate("MainWindow", "离散量卡"))
        self.cb_ins_LR.setText(_translate("MainWindow", "LVDT/RVDT"))
        self.cb_ins_429.setText(_translate("MainWindow", "429通信"))
        self.cb_ins_232.setText(_translate("MainWindow", "232通信"))
        self.pb_ins_confirm.setText(_translate("MainWindow", "确定"))
        self.label_2.setText(_translate("MainWindow", "设备模式与保护设定"))
        self.label_3.setText(_translate("MainWindow", "28Vdc直流电源"))
        self.label_6.setText(_translate("MainWindow", "过载保护"))
        self.le_pro_dc_overcur.setText(_translate("MainWindow", "10"))
        self.label_4.setText(_translate("MainWindow", "A"))
        self.label_5.setText(_translate("MainWindow", "过压保护"))
        self.le_pro_dc_overvolt.setText(_translate("MainWindow", "30"))
        self.label_7.setText(_translate("MainWindow", "V"))
        self.label_8.setText(_translate("MainWindow", "115Vdc交直流电源"))
        self.rb_pro_adc_single.setText(_translate("MainWindow", "单相"))
        self.rb_pro_adc_low.setText(_translate("MainWindow", "LOW"))
        self.rb_pro_adc_high.setText(_translate("MainWindow", "HIGH"))
        self.label_43.setText(_translate("MainWindow", "低压保护"))
        self.label_40.setText(_translate("MainWindow", "A"))
        self.label_42.setText(_translate("MainWindow", "V"))
        self.le_pro_ac_overvolt.setText(_translate("MainWindow", "120"))
        self.label_41.setText(_translate("MainWindow", "过压保护"))
        self.label_39.setText(_translate("MainWindow", "过载保护"))
        self.le_pro_ac_overcur.setText(_translate("MainWindow", "5"))
        self.label_45.setText(_translate("MainWindow", "过功率保护"))
        self.le_pro_ac_lowvolt.setText(_translate("MainWindow", "100"))
        self.le_pro_ac_overPpro.setText(_translate("MainWindow", "600"))
        self.label_44.setText(_translate("MainWindow", "V"))
        self.label_46.setText(_translate("MainWindow", "W"))
        self.pb_pro.setText(_translate("MainWindow", "确定"))
