# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(742, 346)
        MainWindow.setStyleSheet("background-color: rgb(58, 58,58);\n"
"QLineEdit{\n"
"    color:white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.lb_username_2 = QtWidgets.QLabel(self.centralwidget)
        self.lb_username_2.setStyleSheet("font-family:Arial;\n"
"                                            font-size:40px;\n"
"\n"
"                                            color:rgb(255, 255, 255)\n"
"                                        ")
        self.lb_username_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_username_2.setObjectName("lb_username_2")
        self.verticalLayout_2.addWidget(self.lb_username_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.lb_username = QtWidgets.QLabel(self.centralwidget)
        self.lb_username.setStyleSheet("font-family:Arial;\n"
"                                            font-size:25px;\n"
"\n"
"                                            color:rgb(255, 255, 255)\n"
"                                        ")
        self.lb_username.setObjectName("lb_username")
        self.horizontalLayout.addWidget(self.lb_username)
        self.le_username = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(8)
        self.le_username.setFont(font)
        self.le_username.setTabletTracking(True)
        self.le_username.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.le_username.setStyleSheet("color:white;\n"
"background-color: rgb(0, 0, 0);\n"
"font: 65 14pt \"Arial\";")
        self.le_username.setAlignment(QtCore.Qt.AlignCenter)
        self.le_username.setClearButtonEnabled(True)
        self.le_username.setObjectName("le_username")
        self.horizontalLayout.addWidget(self.le_username)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.lb_password = QtWidgets.QLabel(self.centralwidget)
        self.lb_password.setStyleSheet("font-family:Arial;\n"
"                                            font-size:25px;\n"
"\n"
"                                            color:rgb(255, 255, 255)\n"
"                                        ")
        self.lb_password.setObjectName("lb_password")
        self.horizontalLayout_2.addWidget(self.lb_password)
        self.le_password = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(8)
        self.le_password.setFont(font)
        self.le_password.setStyleSheet("color:white;\n"
"background-color: rgb(0, 0, 0);\n"
"font: 65 14pt \"Arial\";")
        self.le_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_password.setAlignment(QtCore.Qt.AlignCenter)
        self.le_password.setClearButtonEnabled(True)
        self.le_password.setObjectName("le_password")
        self.horizontalLayout_2.addWidget(self.le_password)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.pb_login = QtWidgets.QPushButton(self.centralwidget)
        self.pb_login.setStyleSheet("QPushButton {\n"
"                                            color: #ffffff;\n"
"                                            background-color: rgb(40,40, 60);\n"
"                                            border-radius:5px;\n"
"                                            text-align:center;\n"
"                                            font-size:20pt;\n"
"                                            font-family:Arial;\n"
"                                            padding: 5px;\n"
"                                            border:2px solid rgb(67,83,180);\n"
"                                            }\n"
"                                            QPushButton:hover{\n"
"                                            font-size:20pt;\n"
"                                            font-weight:bold;\n"
"                                            border-width:4px;\n"
"                                            border-radius:10px;\n"
"                                            }\n"
"                                        ")
        self.pb_login.setObjectName("pb_login")
        self.horizontalLayout_3.addWidget(self.pb_login)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pb_login.clicked.connect(MainWindow.slot_pb_login) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "登录"))
        self.lb_username_2.setText(_translate("MainWindow", "登录界面"))
        self.lb_username.setText(_translate("MainWindow", "用户名："))
        self.lb_password.setText(_translate("MainWindow", "密    码："))
        self.pb_login.setText(_translate("MainWindow", "登 录"))
        self.pb_login.setShortcut(_translate("MainWindow", "Return"))
