tab_change={0:["power_on", '供电设备上电'], 1:["sends", '控制指令测试'], 2:["DI", '离散量输入测试'],
            3:["DO", '离散量输出驱动测试'],4: ["AI", '模拟量输入测试'], 5:["AO", '模拟量输出测试'],6:["carProtect", '超转保护与停车测试']}
all_data={'AI': {'control_button': {0: 'pushButton_2', 1: 'pushButton_3', 2: 'pushButton_4', 3: 'pushButton_5',
                                   4: 'pushButton_6', 5: 'pushButton_7', 6: 'pushButton_8', 7: 'pushButton_9',
                                   8: 'pushButton_12', 9: 'pushButton_10', 10: 'pushButton_11', 11: 'pushButton_13',
                                   12: 'pushButton_17', 13: 'pushButton_19', 14: 'pushButton_21', 15: 'pushButton_14',
                                   16: 'pushButton_15'},
            'control_lineedit': {0: 'dsb_auto_ai_AIN_EDT_3', 1: 'dsb_auto_ai_AIN_NVT_3', 2: 'dsb_auto_ai_AIN_SVM_3',
                                 3: 'dsb_auto_ai_AIN_KTM_15', 4: 'dsb_auto_ai_AIN_KTM_13', 5: 'dsb_auto_ai_AIN_KTM_12',
                                 6: 'dsb_auto_ai_AIN_KTM_11', 7: 'dsb_auto_ai_AIN_KTM_14', 8: 'cm_auto_ai_AIN_PT100_9',
                                 9: 'cm_auto_ai_AIN_PT100_8', 10: 'cm_auto_ai_AIN_PT100_7',
                                 11: 'cm_auto_ai_AIN_CTSENSOR_3', 12: 'le_auto_ai_SCVIN_3', 13: 'le_auto_ai_IGV_IN_3',
                                 14: 'le_auto_ai_RVDTIN_3', 15: 'dsb_auto_ai_AIN_FRE_N1_6',
                                 16: 'dsb_auto_ai_AIN_FRE_N1_5'},
            'control_relinedit': {0: 'le_auto_ai_AIN_EDTr_3', 1: 'le_auto_ai_AIN_NVTr_3', 2: 'le_auto_ai_AIN_SVMr_3',
                                  3: 'le_auto_ai_AIN_KTM_1r_3', 4: 'le_auto_ai_AIN_KTM_2r_3',
                                  5: 'le_auto_ai_AIN_KTM_3r_3', 6: 'le_auto_ai_AIN_KTM_4r_3',
                                  7: 'le_auto_ai_AIN_KTM_5r_3', 8: 'le_auto_ai_AIN_PT100_1r_3',
                                  9: 'le_auto_ai_AIN_PT100_2r_3', 10: 'le_auto_ai_AIN_PT100_3r_3',
                                  11: 'le_auto_ai_AIN_CTSENSORr_3', 12: 'le_auto_ai_SCVOUT_3',
                                  13: 'le_auto_ai_IGVOUT_3', 14: 'le_auto_ai_RVDTOUT_3', 15: 'le_auto_ai_AIN_FRE_N1r_3',
                                  16: 'le_auto_ai_AIN_FRE_N2r_3'},
            'sort_class': {0: '5vdc', 1: '5vdc', 2: '28vdc', 3: 'mvdc', 4: 'mvdc', 5: 'mvdc', 6: 'mvdc', 7: 'mvdc',
                           8: 'mvdc', 9: 'r', 10: 'r', 11: 'r', 12: 'ac', 13: 'ac', 14: 'ac', 15: 'ac', 16: 'ac'},
            "delay_data":{0:15,1:16,2:14,3:9,4:10,5:13,6:11,7:12,8:41,9:42},
            "sends_input":"pte_auto_ai_insIN_3",
            "sends_output":"pte_auto_ai_insOUT_3"
        }}
